/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternP;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ds2400
 */
public class Login extends javax.swing.JFrame {

  public Connection con;
   public Statement st;
    
  
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        this.setTitle("Shank Ventures Ltd. ");
   
       
        try{
        Class.forName("com.mysql.jdbc.Driver");
       con =DriverManager.getConnection("jdbc:mysql://localhost:3306/Shank","root","");
       st=con.createStatement();
       }
       catch(Exception ex)
               {
               System.out.println(ex);
               }
         
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ph = new javax.swing.JPasswordField();
        em1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Grow Your Buisness with ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 0, 200, 40);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setBackground(new java.awt.Color(0, 102, 153));
        jToggleButton1.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Login with Google");
        jToggleButton1.setBorder(null);
        jPanel2.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 215, 32));

        jToggleButton2.setBackground(new java.awt.Color(204, 204, 204));
        jToggleButton2.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        jToggleButton2.setText(" LOGIN");
        jToggleButton2.setBorder(null);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 90, 30));

        jToggleButton3.setBackground(new java.awt.Color(0, 102, 153));
        jToggleButton3.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jToggleButton3.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton3.setText("   Login with Fb  ");
        jToggleButton3.setBorder(null);
        jPanel2.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 215, 32));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("OR");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InternP/google.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 21, 32));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InternP/fb.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 33));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login Here ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 140, 40));

        ph.setBackground(new java.awt.Color(204, 204, 204));
        ph.setText("jPasswordField1");
        ph.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phMouseClicked(evt);
            }
        });
        jPanel2.add(ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 210, 30));

        em1.setBackground(new java.awt.Color(204, 204, 204));
        em1.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        em1.setText("  Email Id");
        em1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        em1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                em1MouseClicked(evt);
            }
        });
        em1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                em1ActionPerformed(evt);
            }
        });
        jPanel2.add(em1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 210, 31));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 40));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email Id:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 40));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(230, 10, 352, 210);

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Shank");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 70, 37);

        jButton2.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 260, 61, 34);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InternP/Girl-using-laptop-850x491.jpeg"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(-30, 0, 650, 320);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        
         try{
         
       String l1="Select * from register where Email='"+em1.getText()+"' and password='"+ph.getText()+"';";
        String online="Update register set online='"+1+"' where Email='"+em1.getText()+"';";
         //String s1 = em1.getText();
       
        
        
             st.addBatch(online);
             st.executeBatch();
            // ps.setString(3,jTextField5.getText());
             //ps.setString(4,jTextField1.getText());
             
             ResultSet rs=st.executeQuery(l1);
             if(rs.next())
             {
                JOptionPane.showMessageDialog(null, "Login Successful !");
                 this.setVisible(false);
               
                new Aircondition().setVisible(true);
                
               
             }
             
            else{
                JOptionPane.showMessageDialog(null,"Email Id not Found  ! ");
            }
             }
        
        
catch(Exception e)
        {
            System.out.print(e);
        JOptionPane.showMessageDialog(null,"Error");
        }
                                            
        
        /*String s1=em.getText();
        
         try  
          {
                 
                       if(s1.trim().isEmpty())
                       {
                        JOptionPane.showMessageDialog(null,"Fields left blank\nPlease Fill All Fields");
                       }
                       else if(!s1.contains("@"))
                       {
                           JOptionPane.showMessageDialog(null,"Incorrect Email  !");
                       }
                        else if(!s1.contains(".com"))
                       {
                           JOptionPane.showMessageDialog(null,"Provide a Valid Email-Id  !");
                       }
                       else
                       ps=(com.mysql.jdbc.PreparedStatement) con.prepareStatement("select * from login where Email=?");
                       ps.setString(1,em.getText());
                       ResultSet rs;
                       rs=ps.executeQuery();
                       
                        if(rs.next())
                       {
                           JOptionPane.showMessageDialog(null,"This Email Id is already registered. !");
                       }
                       else

                    
                           {
                           ps= (com.mysql.jdbc.PreparedStatement) con.prepareStatement("insert into login values(?)");
                           ps.setString(1, s1);
                          
                           
                           
                           
                           JOptionPane.showMessageDialog(null,"Login Successful");
                           this.setVisible(false);
                           new Aircondition().setVisible(true);
                           
                             }
                       }
                       
                             
                      
                   
                
          catch (Exception ex) 
                {
                    System.out.println(ex);
                   JOptionPane.showMessageDialog(null,"No Internet Connectivity");
                } */

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void em1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_em1MouseClicked
        em1.setText("");
    }//GEN-LAST:event_em1MouseClicked

    private void em1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_em1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_em1ActionPerformed

    private void phMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phMouseClicked
        ph.setText("");
    }//GEN-LAST:event_phMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField em1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JPasswordField ph;
    // End of variables declaration//GEN-END:variables
}
