/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternP;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Ds2400
 */
public class Next extends javax.swing.JFrame {
    Connection con;
PreparedStatement ps; 
    private String typee;

    /**
     * Creates new form Next
     */
    public Next() {
        initComponents();
        
        this.setTitle("Shank Ventures Ltd. ");
         try{  
        Class.forName("com.mysql.jdbc.Driver");
       con =DriverManager.getConnection("jdbc:mysql://localhost:3306/Shank","root","");
       
       }
       catch(Exception ex)
               {
               System.out.println(ex);
               }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        com = new javax.swing.JRadioButton();
        indi = new javax.swing.JRadioButton();
        emai = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        city = new javax.swing.JComboBox<>();
        locate = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ph = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 20)); // NOI18N
        jLabel1.setText("Registration Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 179, 28));

        name.setBackground(new java.awt.Color(204, 204, 204));
        name.setText("Name");
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 72, 212, 35));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        jLabel2.setText("Join As");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 56, 29));

        com.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(com);
        com.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        com.setText("Company");
        com.setBorder(null);
        com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comActionPerformed(evt);
            }
        });
        jPanel1.add(com, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, 29));

        indi.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(indi);
        indi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        indi.setText("Individual");
        indi.setBorder(null);
        indi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiActionPerformed(evt);
            }
        });
        jPanel1.add(indi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, 29));

        emai.setBackground(new java.awt.Color(204, 204, 204));
        emai.setText("Email Id");
        emai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emaiMouseClicked(evt);
            }
        });
        jPanel1.add(emai, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 209, 37));

        jToggleButton1.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jToggleButton1.setText("Next");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 210, 36));

        city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Noida", "Delhi", "Meerut", "Ghaziabad" }));
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 140, 212, 34));

        locate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sector 55", "R.K.Puram", "Karol Bagh" }));
        jPanel1.add(locate, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 216, 212, 33));

        jButton1.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 274, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Select Location:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 100, 20));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Select City:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 70, -1));

        ph.setBackground(new java.awt.Color(204, 204, 204));
        ph.setText("jPasswordField1");
        ph.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phMouseClicked(evt);
            }
        });
        ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phActionPerformed(evt);
            }
        });
        jPanel1.add(ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 210, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InternP/Girl-using-laptop-850x491.jpeg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        name.setText("");
    }//GEN-LAST:event_nameMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String s1 = name.getText();
          String s2 = city.getSelectedItem().toString();
          String s3 = locate.getSelectedItem().toString();
        
            String s4 = type;
            String s5 = emai.getText();
            String s6= ph.getText();
           
     
            
          
            
            try  
          {
                 
                       if(s1.trim().isEmpty()||s2.trim().isEmpty()||s3.trim().isEmpty()||s4.trim().isEmpty()||s5.trim().isEmpty()||s6.trim().isEmpty())
                       {
                        JOptionPane.showMessageDialog(null,"Fields left blank\nPlease Fill All Fields");
                       }
                        else if(!s5.contains("@"))
                       {
                           JOptionPane.showMessageDialog(null,"Incorrect Email  !");
                       }
                        else if(!s5.contains(".com"))
                       {
                           JOptionPane.showMessageDialog(null,"Provide a Valid Email-Id  !");
                       }
                      else
                       ps=(com.mysql.jdbc.PreparedStatement) con.prepareStatement("select * from register where Email=?");
                       ps.setString(1,emai.getText());
                       ResultSet rs;
                       rs=ps.executeQuery();
                       
                        if(rs.next())
                       {
                           JOptionPane.showMessageDialog(null,"This Email Id is already registered. !");
                       } 
                 
                       else
                       {
                       ps= (com.mysql.jdbc.PreparedStatement) con.prepareStatement("insert into register values(?,?,?,?,?,?,0,0,0,0,0,0,0)");
                          ps.setString(1, s1);
                          ps.setString(2, s2);
                          ps.setString(3, s3);
                          ps.setString(4, s4);
                          ps.setString(5, s5);
                          ps.setString(6, s6);
                         
                        
                          
                          ps.executeUpdate();
                          JOptionPane.showMessageDialog(null," You have Registered Successfully");
                          
                          ps.close();
                          
                      
                      this.setVisible(false);
                      //new start().setVisible(true);
                       
                       
                       }
                       
                   
                }
          catch (Exception ex) 
                {
                    System.out.println(ex);
                    JOptionPane.showMessageDialog(null,"  No Internet Connectivity.");
                }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void emaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emaiMouseClicked
       emai.setText("");
    }//GEN-LAST:event_emaiMouseClicked

    private void comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comActionPerformed
         type = "Company";
    }//GEN-LAST:event_comActionPerformed

    private void indiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiActionPerformed
        type = "Individual";
    }//GEN-LAST:event_indiActionPerformed

    private void phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phActionPerformed

    private void phMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phMouseClicked
         ph.setText("");
    }//GEN-LAST:event_phMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Next.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Next.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Next.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Next.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Next().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> city;
    private javax.swing.JRadioButton com;
    private javax.swing.JTextField emai;
    private javax.swing.JRadioButton indi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> locate;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField ph;
    // End of variables declaration//GEN-END:variables

    
   String type;
}
